### ISSUE TITLE
CustomTestSets may be broken

### ISSUE THREAD

**Issue by mmiller-max** [JuliaTesting/TestReports.jl#61]
I think the below means that it no longer works with a `CustomTestSet` unless they have the correct fields.

https://github.com/JuliaTesting/TestReports.jl/blob/3fe754ca3d72d40c5740c9e8d446c6a22839a207/src/testsets.jl#L234

This clashes with our documentation, and it think should be fixed as it would be nice to still be able to use `CustomTestSet`s. This should be added to the V1.0 roadmap too.

**Comment by adolgert** [comment]
I see this is on the roadmap. There is a customer for this issue: fjarri/Jute.jl uses a custom test set that's derived from AbstractTestSet. It would work with TestReports.jl if the `function to_xml(ts::ReportingTestSet)` also included `function to_xml(ts::Test.AbstractTestSet)` that assumes the type has a description and results, but no properties. That would mean Jute.jl could use the same C.I. pipeline as Test, thanks to the way TestReports uses test sets. Thank you for making this so compatible!

**Comment by oxinabox** [comment]
It seems quite possible that the `JuteTestset` type is not needed.
It seems like it acts just like a `DefaultTestset`, and that a `ReportingTestset` would thus also work.
Tht would just be changing https://github.com/fjarri/Jute.jl/blob/421c6c9b47f0150c246cec0005fb8b98a8d5b5f1/src/run_testcase.jl#L149
to  `Test.@testset JuteTestSet "$(tc.name)" begin` (so that it will use what ever the testset of its parent is, which in this case would be a `ReporttingTestset`
and then adding inside it a little call to to` get_testset` so it can exflitrate the `results` field.

---

But still we should support recording abitary testsets.
We should just drop any of the fields (like timing info) that we don't have access to.

**Comment by adolgert** [comment]
You're both quick and correct! And, with a good use of "exfiltrate." I suspect Bogdan (fjarri) has plans around that type. For instance, this is where you would store a timeout in case a test runs long. I can ask, though.
